disabled_rules:
    - trailing_whitespace
    - unused_closure_parameter
    - identifier_name
opt_in_rules:
    - empty_count
    - empty_string
excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
analyzer_rules:
    - explicit_self
type_name:
    min_length: 2
line_length:
    warning: 200
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 8
    error: 10
type_body_length:
    warning: 500
    error: 1000
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 20
    error: 25
reporter: "xcode"
